# Site settings
title: "Aamir Azhar"
email: aamirazhar@gmail.com
description: "Just a kid trying to make sense of the world around him."
baseurl: ""
url: "https://aamirazhar.me/"
title_description: "My name is Aamir Azhar. I'm a 20 year old kid who studies Computer Science,
Arabic, and Documentary Studies at Duke University. This blog is mostly social/political commentary, poetry/creative writing, and maybe the occasional book/film/album review. If you only want to read a certain kind of post, go to http://www.aamirazhar.me/posts-by-categories/.

And fair warning, my creative writing is somewhat emotional or exaggerated, so skip it if you don't know me like that. Hope you enjoy, and please feel free to leave a comment or some feedback."
title_image: "https://i.imgur.com/jsKk9b4.jpg"
google_analytics: "UA-79202944-1"
disqus_account: aamirazhar
github_repository: https://github.com/kupoko/aamirazhar.me
addthis_id: ra-575cb03f29af3a6d
post_limit: 5

# Social usernames/URLs
facebook_username: aamirazhar
tumblr_username: kupoko
github_username:  kupoko
twitter_username: aamir_azhar
linkedin_username: aamir-azhar-a5060a3
google_plus_userame: AamirAzhar11

# Footer
footer_left: "Carte Noire theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/kupoko/aamirazhar.me\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
