# Site settings
title: "Yury Voloshin"
email: yvoloshin01@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://yvoloshin.github.io"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "http://i.imgur.com/VSI9h3S.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://yvoloshin.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  yvoloshin
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
